### ISSUE TITLE
Sourcemod 1.11

### ISSUE THREAD

**Issue by ByDexterTR** [Hexer10/Sourcemod-HandleDumpParser#6]
SM 1.11 does not work properly with dump files.

**Comment by Adrianilloo** [comment]
Using SM 1.11. When I try upload a dump file (or copy contents), I get a popup on the top right corner with the error "Invalid string!" marked in red

**Comment by Hexer10** [comment]
I apologize for noticing this issue only now.
Unfortunately at the moment I don't have any test server running sm 1.11, so it would really helpful if someone could provide a dump

**Comment by ddorab** [comment]
https://mystb.in/SuperintendentFinishingCiao @Hexer10 

I removed the time createds myself

**Comment by ddorab** [comment]
![image](https://user-images.githubusercontent.com/45337750/207350255-3507c542-63f1-4285-9ee6-7ef2ac5afe68.png)

**Comment by Adrianilloo** [comment]
On side note, I would like to mention the fact that dumps (at least for SM 1.11) cut longer plugin names due to a fixed column size, sadly. I'm not sure if that happened in older SM versions, as well.

In case it always happened, how does this web system deal with this? Otherwise, it should be a problem.

**Comment by Kxnrl** [comment]
still report ``invalid string``
